// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The catalog of scored records Service2 currently serves
    #
    # + return - The current catalog; empty when Service2 is in empty mode
    resource function get catalog() returns Catalog {
        return getCatalogSnapshot();
    }

    resource function put catalog\-mode(@http:Payload CatalogMode payload) returns CatalogMode|ErrorBadRequest {
        return applyCatalogMode(payload.mode);
    }
}

public type CatalogMode record {
    # full serves the ten seeded records; empty serves no records
    string mode;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type Record record {
    int id;
    string name;
    int score;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type Catalog record {
    # Number of records in the catalog
    int count;
    Record[] records;
};
